INSERT INTO pays (nom_pays, continent)
VALUES ('France', 'Europe'),
('Espagne', 'Europe'),
('Angleterre', 'Europe'),
('Allemagne', 'Europe'),
('Italie', 'Europe'),
('Chine', 'Asie'),
('Portugal', 'Europe'),
('Niger', 'Afrique'),
('Canada', 'Amerique du Nord'),
('Mexique', 'Amerique du Sud'),
('Autralie', 'Oceanie'),
('Russie', 'Europe'),
('Japon', 'Asie'),
('Inde', 'Asie'),
('Bresil', 'Amerique du Sud'),
('Argentine', 'Amerique du Sud'),
('Chili', 'Amerique du Sud'),
('Perou', 'Amerique du Sud'),
('Colombie', 'Amerique du Sud'),
('Venezuela', 'Amerique du Sud'),
('Equateur', 'Amerique du Sud'),
('Bolivie', 'Amerique du Sud'),
('Paraguay', 'Amerique du Sud'),
('Uruguay', 'Amerique du Sud'),
('Suriname', 'Amerique du Sud'),
('Guyane', 'Amerique du Sud'),
('Panama', 'Amerique du Sud'),
('Costa Rica', 'Amerique du Sud'),
('Cuba', 'Amerique du Sud'),
('Haiti', 'Amerique du Sud'),
('Jamaique', 'Amerique du Sud'),
('Bahamas', 'Amerique du Sud'),
('Puerto Rico', 'Amerique du Sud'),
('Belize', 'Amerique du Sud'),
('Honduras', 'Amerique du Sud'),
('Nicaragua', 'Amerique du Sud'),
('Salvador', 'Amerique du Sud'),
('Guatemala', 'Amerique du Sud'),
('Belize', 'Amerique du Sud'),
('Honduras', 'Amerique du Sud'),
('Nicaragua', 'Amerique du Sud'),
('Salvador', 'Amerique du Sud'),
('Guatemala', 'Amerique du Sud'),
('Etats-Unie', 'Amerique du Nord');


INSERT INTO entrepots (nom_entrepot, adresse, id_pays)
VALUES ('Entrepot 1', '1 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 2', '2 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 3', '3 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 4', '4 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 5', '5 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 6', '6 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 7', '7 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 8', '8 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 9', '9 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 10', '10 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 11', '11 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 12', '12 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 13', '13 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 14', '14 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 15', '15 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 16', '16 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 17', '17 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 18', '18 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 19', '19 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 20', '20 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 21', '21 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 22', '22 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 23', '23 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 24', '24 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 25', '25 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 26', '26 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 27', '27 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 28', '28 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 29', '29 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 30', '30 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 31', '31 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 32', '32 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 33', '33 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 34', '34 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 35', '35 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 36', '36 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 37', '37 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 38', '38 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 39', '39 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 40', '40 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 41', '41 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 42', '42 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 43', '43 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 44', '44 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 45', '45 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 46', '46 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 47', '47 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 48', '48 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)), 
('Entrepot 49', '49 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 50', '50 rue de la paix', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('Entrepot 51', '51 rue de la paix', 1), -- france
('Entrepot 52', '52 rue de la paix', 6); -- chine

INSERT INTO expeditions (date_expedition, id_entrepot_source, id_entrepot_destination, poids, statut, date_livraison, date_livraison_estimee)
VALUES 
('2020-02-04', 51 , 52 ,532, 'En transit', DATE_ADD('2020-02-04', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-02-04', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)), -- en transite d'europe to asia
('2020-01-01', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 10, 'Livré', DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-02', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 20, 'En transit', DATE_ADD('2020-01-02', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-02', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-03', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 30, 'En transit', DATE_ADD('2020-01-03', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-03', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-04', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 40, 'En transit', DATE_ADD('2020-01-04', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-04', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-05', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 50, 'En transit', DATE_ADD('2020-01-05', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-05', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-06', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 60, 'Livré', DATE_ADD('2020-01-06', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-06', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-07', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 70, 'En transit', DATE_ADD('2020-01-07', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-07', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-08', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 80, 'Livré', DATE_ADD('2020-01-08', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-08', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-09', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 90, 'En transit', DATE_ADD('2020-01-09', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-09', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-10', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 100, 'Livré', DATE_ADD('2020-01-10', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-10', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-11', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 110, 'Livré', DATE_ADD('2020-01-11', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-11', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-12', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 120, 'Livré', DATE_ADD('2020-01-12', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-12', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-13', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 130, 'Livré', DATE_ADD('2020-01-13', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-13', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-14', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 140, 'Livré', DATE_ADD('2020-01-14', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-14', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-15', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 150, 'Livré', DATE_ADD('2020-01-15', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-15', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-16', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 160, 'Livré', DATE_ADD('2020-01-16', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-16', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-17', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 170, 'Livré', DATE_ADD('2020-01-17', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-17', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-18', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 180, 'Livré', DATE_ADD('2020-01-18', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-18', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-19', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 190, 'Livré', DATE_ADD('2020-01-19', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-19', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2020-01-20', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), 200, 'Livré', DATE_ADD('2020-01-20', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-20', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2018-01-21', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),210, 'En transit', DATE_ADD('2020-01-21', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-21', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2018-01-22', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),220, 'En transit', DATE_ADD('2020-01-22', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-22', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2018-01-23', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),230, 'En transit', DATE_ADD('2020-01-23', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-23', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2023-01-24', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),240, 'Livré', DATE_ADD('2020-01-24', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-24', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2023-01-25', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),250, 'Livré', DATE_ADD('2020-01-25', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-25', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2023-01-26', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),260, 'En transit', DATE_ADD('2020-01-26', INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD('2020-01-26', INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY));


INSERT INTO expeditions (date_expedition, id_entrepot_source, id_entrepot_destination, poids, statut, date_livraison, date_livraison_estimee)
VALUES 
('2023-11-23', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),210, 'En transit', DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2023-11-22', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),210, 'En transit', DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY)),
('2023-11-12', (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1), (SELECT id FROM entrepots ORDER BY RAND() LIMIT 1),210, 'En transit', DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 10) DAY), DATE_ADD(DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 10) DAY), INTERVAL FLOOR(RAND() * 3 - 1) DAY));



--Ajoutez des données aux tables "clients" et "expeditions_clients".
INSERT INTO clients (nom, adresse, ville, id_pays)
VALUES
('client 1', '1 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 2', '2 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 3', '3 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 4', '4 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 5', '5 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 6', '6 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 7', '7 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 8', '8 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 9', '9 rue de la paix', 'Paris', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 10', '10 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 11', '11 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 12', '12 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 13', '13 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 14', '14 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 15', '15 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 16', '16 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1)),
('client 17', '17 rue de la paix', 'Londres', (SELECT id FROM pays ORDER BY RAND() LIMIT 1));

INSERT INTO expeditions_clients (id_expedition, id_client)
VALUES
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1)),
((SELECT id FROM expeditions ORDER BY RAND() LIMIT 1), (SELECT id FROM clients ORDER BY RAND() LIMIT 1));